#!/bin/bash
#SBATCH --job-name=botrytis_anova
#SBATCH --output=/home/ccdepeel/kliebengrp/botrytis_anova/output/botrytis_%j.out
#SBATCH --error=/home/ccdepeel/kliebengrp/botrytis_anova/output/botrytis_%j.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ccdepeel@ucdavis.edu
#SBATCH --account=publicgrp
#SBATCH --partition=low
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G

module load R
Rscript /home/ccdepeel/r-ANOVA-botrytiscombinedprotein/ANOVAtest_v2.R \
  /home/ccdepeel/kliebengrp/botrytis_anova/data/"Botrytis_combined_protein.tsv.xlsx - combined_protein.csv" \
  /home/ccdepeel/kliebengrp/botrytis_anova/output/