#!/bin/bash
#SBATCH --job-name=lesionTrainGPU
#SBATCH --output=lesionTrainGPU_%j.out
#SBATCH --error=lesionTrainGPU_%j.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ccdepeel@ucdavis.edu
#SBATCH --account=publicgrp
#SBATCH --partition=gpul
#SBATCH --gres=gpu:1
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G

module load R

# Define input file paths
COUNTS_FILE1=$1
OUTPUT_DIR=$2

Rscript ~/r-ANOVA-botrytiscombinedprotein/ANOVAtest_v2.R \
"$COUNTS_FILE1" \
"$OUTPUT_DIR"